### ISSUE TITLE
[Feature] automate (most parts of) the release process in CI

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#11225]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This issue is to track the works that we need to do, to automate our release process.

## What we have done

- [x] [Docker images can be published automatically](https://github.com/apache/skywalking/blob/master/.github/workflows/publish-docker.yaml) after a GitHub release.

## What we want to achieve further

Automate everything needed in a release, except for the step to "close the repository in Apache Nexus Staging repositories".

Voters still need to manually check the release artifacts by hand.

### Prerequisites

- [ ] Make sure the builds are reproducible. Reproducible build means, given the same source code revision, anyone on earth can build the exactly same (bit-by-bit) binary tarball, usually this can be roughly verified with the shasum of the tarball.

### Tasks

- [ ] Publish the packages to maven staging repository when creating a pre-release candidate, at the same time,
- [ ] build the binary tarball, generate shasum, sign the tarball with GPG key, and save to Apache SVN staging folder,
- [ ] generate the voting email content, release manager can copy the content and send for vote,
- [ ] when promoting the pre-release candidate to a release on GitHub, move the binary tarball from SVN staging folder to the release folder, at the same time,
- [ ] delete older releases in SVN,
- [ ] generate the content of announcement email.

### Are you willing to submit a pull request to implement this on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Which GPG key would be used in the signing process of the release? Would the INFRA provide one?

**Comment by kezhenxu94** [comment]
As reproducible builds are the first prerequisite of all, here I'm kindly requesting some active contributors to help verify in all possible environments/machines they have, here are some steps to do to verify our builds are reproducible:

- Tell us the OS you tested

```
uname -a
Linux develop 5.13.0-1033-gcp #40-Ubuntu SMP Mon Jun 13 20:57:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

- Make sure to install the Temurin-11.0.18+10 JDK, download from [the official website](https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.18%2B10) or use [asdf](https://asdf-vm.com/guide/getting-started.html) and [asdf java plugin](https://github.com/halcyon/asdf-java) to manage multiple JDK versions.

```
java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)
```

- Check out the source code revision `034a68b100f42a169ebcc7dd653bd13a1e8617ab`

```
git reset --hard 034a68b100f42a169ebcc7dd653bd13a1e8617ab
git status 
# make sure the working tree is clean
```

- Build the binary


```
./mvnw clean install javadoc:javadoc -B -q -Pall -Dmaven.test.skip -Dcheckstyle.skip
```

- Share the shasum of your outcome.

```
shasum apm-dist/target/apache-skywalking-apm-bin.tar.gz 
```

According to the security team, we need at least 2 committers to verify the builds are reproducible and cross check with each other (@wu-sheng and if you think someone else is willing to help, please tag them). Here is the shasum of my build, from the source code revision mentioned above, I cross check this on a Linux VM and on my local MacBook Pro, they produced the same tarball:


```
8a49192dcf62b3cda7b145ea631f222d35ab1470  apm-dist/target/apache-skywalking-apm-bin.tar.gz
```

If anyone has a Windows system to verify this, it would be better.

**Comment by kezhenxu94** [comment]
> Which GPG key would be used in the signing process of the release? Would the INFRA provide one?

All related keys will be provided by infra as we request, GPG key, SVN user/pass, etc., no personal key from any individual.

**Comment by wu-sheng** [comment]
- OS

> Darwin Wu-Shengs-MacBook-Pro-14.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

- Java version

> openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

- shasum

> dbb66ea4ea4dd8844966ea154306bc3af92b02e1  apm-dist/target/apache-skywalking-apm-bin.tar.gz

___
I am not sure, does diff CPU matter? I am using the AARM(Apple Silicon).

**Comment by wu-sheng** [comment]
Close as we are not working on this.
