### ISSUE TITLE
[Bug] Tracking Kafka consumer causes web page to crash.

### ISSUE THREAD

**Issue by deity-z** [apache/skywalking#11228]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Currently, I am tracking Kafka consumers. However, when I click on the Kafka trace, if the duration is short, the results are displayed quickly. But for long-duration traces, the web page crashes. What configurations need to be modified? [https://saas-wk.wksaas.net/IMG-H-ab6ba4b6-8d39-4ef8-8c7e-55beb2005cff?attname=4444.png](url)

### What you expected to happen

Currently, I am tracking Kafka consumers. However, when I click on the Kafka trace, if the duration is short, the results are displayed quickly. But for long-duration traces, the web page crashes. What configurations need to be modified? [https://saas-wk.wksaas.net/IMG-H-ab6ba4b6-8d39-4ef8-8c7e-55beb2005cff?attname=4444.png](url)

### How to reproduce

Currently, I am tracking Kafka consumers. However, when I click on the Kafka trace, if the duration is short, the results are displayed quickly. But for long-duration traces, the web page crashes. What configurations need to be modified? [https://saas-wk.wksaas.net/IMG-H-ab6ba4b6-8d39-4ef8-8c7e-55beb2005cff?attname=4444.png](url)

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by deity-z** [comment]
![image](https://github.com/apache/skywalking/assets/60026740/296b06f4-3d9d-460d-92f6-3bd78496fc97)
It appears that when it took 60 to 70 years to expand the web page directly crashed

**Comment by deity-z** [comment]
It appears that when it took 60 to 70 years to expand the web page directly crashed
