### ISSUE TITLE
[Feature] PHP extension supports link tracking sampling rate configuration

### ISSUE THREAD

**Issue by elricli** [apache/skywalking#12043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Like:
- `skywalking.sample_n_per_3_secs` in the [SkyAPM/SkyAPM-php-sdk v4](https://github.com/SkyAPM/SkyAPM-php-sdk/blob/205bfc1c1d15c1fe1f45821a0948562df7bbdec2/skywalking.c#L75) 
- `agent.sampler` in the [skywalking-go](https://github.com/apache/skywalking-go/blob/642606007162e9b6f5c6827e4903994f6364d8fe/tools/go-agent/config/agent.default.yaml#L26) 

### Use case

Added a php.ini configuration: `skywalking_agent.sampler` (Sampling rate of tracing data, which is a floating-point value that must be between 0 and 1.)

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to do this?

**Comment by elricli** [comment]
> Are you going to do this?

I can try

**Comment by wu-sheng** [comment]
SkyWalking issue track is only for on-going things. Feature request is only hosting on the discussion panel to wait for someone picks up.

**Comment by elricli** [comment]
Ok, I created a discussion. #12044
