### ISSUE TITLE
[Feature] Support tracking the message listener of spring jms

### ISSUE THREAD

**Issue by hyhyf** [apache/skywalking#12460]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When using spring boot starter activemq 1.x or 2.x, activemq-5.x-plugin can work well, but more execute details of the consumer are lost, because spring jms use other thread pool to execute listener task, so need a new plugin to handle this problem?

org.springframework.jms.listener.DefaultMessageListenerContainer#doRescheduleTask
![20240717160603](https://github.com/user-attachments/assets/8e9d4e27-a8ad-4621-9203-7bcc83a48b35)

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We can't tell the issue or requirements. The number of use cases is massive.

It could be threaf related, or supported API scope related too.

**Comment by wu-sheng** [comment]
We don't track plugin requirements, because itwis countless.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-java/pull/705
