### ISSUE TITLE
Tracking some tasks for Go Agent 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#2628]
This issue will track some Go Agent related tasks, including:

 - [x] Documenting Go Agent
 - [ ] Documenting essential tags for OAP analyzing
 - [x] Update readme
 - [ ] agent document
 - [ ] Update `components-libraries.yml`

**Comment by wu-sheng** [comment]
Notice, as Go Agent is manually instrumentation, please say that explicitly. Also, at [agent setup page](https://github.com/apache/skywalking/blob/master/docs/en/setup/README.md#language-agents-in-service), you need to refer to the original repo and your go document

**Comment by wu-sheng** [comment]
Go agent has been working well.
