### ISSUE TITLE
Plugin test-cases immigrate plan

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#3583]
This issue is intended to track to immigrate every plugin test-cases back main repo. The plugin test development guide doc is https://github.com/apache/skywalking/blob/master/docs/en/guides/Plugin-test.md

## done list
- [x] httpclient-4.3.x-scenario
- [x] gateway-scenario
- [x] dubbo-scenario
- [x] solrj-scenario
- [x] spring-async-scenario
- [x] spring-scenario
- [x] jetty-scenario
- [x] kafka-scenario
- [x] canal-scenario
- [x] postgresql-scenario
- [x] sofarpc-scenario
- [x] mongodb-3.x-scenario
- [x] elasticsearch-5.x-scenario
- [x] undertow-routing-scenario
- [x] undertow-scenario
- [x] apm-toolkit-trace-scenario
- [x] ~~dubbox-scenario~~. **Dubbox has been merged into Dubbo officially, the test case is not required.**
- [x] httpasyncclient-scenario
- [x] webflux-scenario
- [x] customize-scenario
- [x] redisson-scenario
- [x] jedis-scenario
- [x] ~~jdk-cross-thread-scenario~~ **This test has been included in apm-toolkit-trace-scenario**.
- [x] feign-scenario
- [x] rabbitmq-scenario
- [x] grpc-scenario
- [x] hystrix-scenario
- [x] okhttp-scenario
- [x] mysql-scenario
- [x] gson-scenario
- [x] pulsar-scenario
- [x] oracle-scenario
- [x] jdk-http-scenario
- [x] cassandra-java-driver-3.x-scenario
- [x] lettuce-scenario
- [x] servicecomb-0.x-scenario
- [x] zookeeper-scenario
- [x] shardingsphere-scenario
- [x] play-scenario
- [x] activemq-scenario
- [x] h2-struts-scenario
- [x] vertx-eventbus-3.x-scenario
- [x] vertx-web-3.x-scenario

## todo list
- [ ] header-scenario
- [ ] light4j-1.6.x-scenario
- [ ] motan-scenario
- [ ] resteasy-scenario
- [ ] rocketMQ-scenario
- [ ] spring-with-qualified-op-name-scenario
- [ ] spring-with-request-method-op-name-scenario

**Comment by arugal** [comment]
I want to be part of it

**Comment by dmsolr** [comment]
1. HttpClient #3579

**Comment by dmsolr** [comment]
> I want to be part of it

Welcome! :)

**Comment by arugal** [comment]
I will immigrate dubbo, ok?

**Comment by wu-sheng** [comment]
> I want to be part of it

@arugal You should know, where are the test cases now, right? We are moving all of them(700+ cases) into the main repo. Huge work to do, definitely need many people's help.

This https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/httpclient-4.3.x-scenario is you should focus on. It is very similar to old test cases and supported by latest test framework. You could ping me on QQ/WeChat, if you need more help.

**Comment by arugal** [comment]
I will immigrate spring scenario and spring async scenario

**Comment by wu-sheng** [comment]
@dmsolr The old repo is read-only today. We will encourage all test cases moving into here by following your framework and review.

https://github.com/SkyAPMTest/agent-auto-integration-testcases

**Comment by arugal** [comment]
I will immigrate kafka scenario

**Comment by arugal** [comment]
I will immigrate canal scenario

**Comment by wu-sheng** [comment]
> I will immigrate canal scenario

Please update the supported-list to add canal(we missed that) at the first level.

**Comment by arugal** [comment]
> > I will immigrate canal scenario
> 
> Please update the supported-list to add canal(we missed that) at the first level.
https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md here?

**Comment by arugal** [comment]
I will immigrate sofarpc scenario

**Comment by wu-sheng** [comment]
324 cases have been moved. Thanks for everyone's help.

**Comment by aderm** [comment]
I will immigrate elasticsearch-5.x-scenario

**Comment by wu-sheng** [comment]
> I will immigrate elasticsearch-5.x-scenario

For elasticsearch client, I could 6.x and 7.x could be tested, if not supported, I hope it could be contributed/added. @aderm

**Comment by wu-sheng** [comment]
> l will immigreate undertow scenario and test whether to support undertow1.x .

If it is, please update the supported-list.md document.

**Comment by aderm** [comment]
> > I will immigrate elasticsearch-5.x-scenario
> 
> For elasticsearch client, I could 6.x and 7.x could be tested, if not supported, I hope it could be contributed/added. @aderm

ok, it's my pleasure.

**Comment by arugal** [comment]
I will immigreate apm-toolkit-trace-scenario

**Comment by wu-sheng** [comment]
@arugal Got it, the case status is just updated.

**Comment by aderm** [comment]
> > > I will immigrate elasticsearch-5.x-scenario
> > 
> > 
> > For elasticsearch client, I could 6.x and 7.x could be tested, if not supported, I hope it could be contributed/added. @aderm
> 
> ok, it's my pleasure. @wu-sheng

@wu-sheng Next, I want to extend es-6.x-plugin，becuause transport is not recommend by elastic official, i will think out http rest client.

**Comment by wu-sheng** [comment]
Make sense to me. I think we could provide a separated 6.x or 7.x plugin.

**Comment by aderm** [comment]
OK

**Comment by aderm** [comment]
@wu-sheng i will immigrate httpasyncclient-scenario

**Comment by tristaZero** [comment]
shardingsphere-scenario for me

**Comment by arugal** [comment]
customize-scenario for me

**Comment by zhaoyuguang** [comment]
webflux-scenario for me

**Comment by zhaoyuguang** [comment]
redisson-scenario for me

**Comment by arugal** [comment]
jedis scenario for me

**Comment by zhaoyuguang** [comment]
zookeeper-scenario & lettuce-scenario for me

**Comment by tomlikeyou** [comment]
jdk-cross-thread-scenario for me

**Comment by arugal** [comment]
@tomlikeyou  Welcome to contribute.

**Comment by arugal** [comment]
> jdk-cross-thread-scenario for me

[apm-toolkit -trace-scenario](https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/apm-toolkit-trace-scenario) has covered ```TraceCrossThread```, so we can give up immigreate [jdk-cross-thread-scenario](https://github.com/SkyAPMTest/agent-auto-integration-testcases/tree/master/jdk-cross-thread-scenario).

**Comment by wu-sheng** [comment]
@arugal You should update the progress, and add the comment like dubbox plugon test.

**Comment by wu-sheng** [comment]
@arugal You should update the progress, and add the comment like dubbox plugon test.

**Comment by arugal** [comment]
grpc scenario for me

**Comment by aderm** [comment]
feign-scenario for me

**Comment by aderm** [comment]
hystrix-scenario for me

**Comment by arugal** [comment]
jdk-http-scenario for me

**Comment by aderm** [comment]
oracle-scenario for me

**Comment by aderm** [comment]
cassandra-java-driver-3.x-scenario for me.

**Comment by arugal** [comment]
servicecomb-0.x-scenario for me

**Comment by wu-sheng** [comment]
> zookeeper-scenario & lettuce-scenario for me

@zhaoyuguang Are you still working on this? One month passed, what is your ETA?

**Comment by zhaoyuguang** [comment]
> > zookeeper-scenario & lettuce-scenario for me
> 
> @zhaoyuguang Are you still working on this? One month passed, what is your ETA?

I will start work next week

**Comment by tuohai666** [comment]
shardingsphere-3.x-scenario for me.

**Comment by wu-sheng** [comment]
@aiyanbo Could you follow this and move play plugin test(https://github.com/SkyAPMTest/agent-auto-integration-testcases/tree/master/play-scenario) into the main repo PR process?

**Comment by aiyanbo** [comment]
> @aiyanbo Could you follow this and move play plugin test(https://github.com/SkyAPMTest/agent-auto-integration-testcases/tree/master/play-scenario) into the main repo PR process?

OK

**Comment by tuohai666** [comment]
shardingsphere-4.x-RC1-RC2-scenario for me.

**Comment by aderm** [comment]
activemq-scenario for me.

**Comment by arugal** [comment]
h2-struts-scenario for me

**Comment by wu-sheng** [comment]
@BFergerson This issue should be updated about the plugin immigration status.

**Comment by BFergerson** [comment]
@wu-sheng, I can't edit the top comment. You can mark off both of these though
```
vertx-eventbus-3.x-scenario
vertx-web-3.x-scenario
```

**Comment by BFergerson** [comment]
@wu-sheng, I'm able to edit comments now. Updated top comment

**Comment by wu-sheng** [comment]
I can see you on the reviewer list now.

**Comment by wu-sheng** [comment]
Close this for now. The new test cases are still welcome. I just feel no point to keep this issue open.
