### ISSUE TITLE
Using Hugo to refactor Apache SkyWalking's website

### ISSUE THREAD

**Issue by rootsongjc** [apache/skywalking#5534]
- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

I propose using [Hugo](https://gohugo.io) to refactor SkyWalking's site, the current site is not user friendly in terms of content organization, and more importantly, the documentation is not put together with the site, you need to jump to GitHub to read the documentation.

I created a prototype of the new website using Hugo, as shown below.

![image](https://user-images.githubusercontent.com/3328185/93853795-206ed200-fce7-11ea-8445-e6fefc74403b.png)

Sections can also be added and customized on the home page. The menu can also be modified. The entire website will be rebuilt in two phases:
- the  first phase migrating the current website to Hugo
- the second phase migrating the documentation to Hugo

Hopefully someone will come along and work with me to refactor the site and make the experience of contributing to SkyWalking and browsing the website more friendly.

**Comment by kezhenxu94** [comment]
> the current site is not user friendly in terms of content organization, 

The site is not meant to be user friendly, I mean the site is mostly updated by SkyWalking maintainer, user friendliness is not our primary concern, but if you have time to polish, it's totally appreciated

> and more importantly, the documentation is not put together with the site

You can build the doc into the website, but if you want to separate the docs parts into the website repo, it's not recommended because we prefer to update the docs together with the codes if any

By the way, there is a rework of the website in progress by a student in the summer code activity mentored by @wu-sheng , maybe you need to wait for that to continue you refactoring?

**Comment by wu-sheng** [comment]
Jimmy had pinged me about this. The progress of the student is far away of what we expected. I would say we could ignore that part.

With our discussion, doc will be kepy where they are today. Jimmy should be able to use CI process  to bind the required tagged and master branch doc.

**Comment by rootsongjc** [comment]
The documentation will remain in the code, it will just be integrated as the site is built, but the documentation in the code will need to be modified to Hugo's format.

**Comment by rootsongjc** [comment]
Now you can see the preview of the new site from <https://skywalking.apache.org/>. This site is built from [rootsongjc/skywalking-webiste](https://github.com/rootsongjc/skywalking-website).

![image](https://user-images.githubusercontent.com/3328185/93987802-97c16600-fdba-11ea-99c8-e033efcea01a.png)

Here are the plans for the three phase of the new website.

## Phase I

**Home page**

1. The SkyWalking logo is missing from navbar, it works on my local computer 😂
1. Add some more sections: latest events, blogs and end users brands
1. Adjust the color scheme to meet the SkyWalking culter
1. Change the background image

**Blog**

1. Modify the display elements of the list to add information such as author and tag.
1. Set the scheme information for the blog(this will be used on every blog post markdown header config)

**Events**

1. Adjust the page layout of a single evnet and fix display errors in the sidebar.

**Team & Downloads**

1. Adjust the layout, some part of the text are covered up.

## Phase II

1. Multi-language support
1. Migrate some blog posts to the website Github repo to test the layout

## Phase III

1. Integration test with the SkyWalking main repository
1. Setup the automation

@Fine0830 Could you help for the UI design and layout of the new website?

**Comment by wu-sheng** [comment]
@rootsongjc Also, we need to add Google/Baidu Analyse to set statistics for the browser as we are moving more things on it. It will help us to know the scope of our community.

The username and password of those platforms should be sent to private@skywalking.apache.org(private mail list). Please ping me before you sent, that mail list requires me manual check for receiving mail from no-PMC members.

**Comment by rootsongjc** [comment]
@wu-sheng Hugo has built-in Google Analytics, to enable it. Do you mean to say create a separate Google Analytics account for this site? Who will turn on Google Analytics, and so will Baidu Tongji.

**Comment by wu-sheng** [comment]
Is Google Analyze able to track Chinese user access? Or we have to set up Baidu Tongji as a backup.

I could create accounts for the project. Do you have the links for creating both?

**Comment by rootsongjc** [comment]
> Is Google Analyze able to track Chinese user access? Or we have to set up Baidu Tongji as a backup.
> 
> I could create accounts for the project. Do you have the links for creating both?

Google Analytics tracking is available in China. But to be on the safe side, you can also configure both traces at the same time. 

- Google Analytics: https://analytics.google.com/analytics/web/
- Baidu tongji: https://tongji.baidu.com/web/welcome/login

**Comment by wu-sheng** [comment]
I have sent you invitations for both platform. If anyone else wants the invitation, please ping me.

**Comment by heyanlong** [comment]
hi, @rootsongjc  great work, far all I know, hugo cannot provide a perfect search solution, how to solve?

**Comment by rootsongjc** [comment]
There are two solutions:
- Google custom search: this is easy to integrate, but not accessible in China
- Algolia: need to do some works to integrate it, you can see the live effect on my [own blog](https://jimmysong.io)

**Comment by rootsongjc** [comment]
Sorry for updating so late. I need help on the front-end and UI side.

I'll start by listing the current front-end issues with the SkyWalking website that was rebuilt using Hugo, and we'll cover the other sections that need to be added later.

Here's a list of issues by page.

### Homepage

Mobile adaptation: let that architecture diagram be adaptive to the page width.

! [image-20201030203129925](https://tva1.sinaimg.cn/large/0081Kckwly1gk7mxe3ordj30lq14mgs7.jpg)

### Blog, event page

Function request: Image click to enlarge full screen (lightbox function)

Optimization: remove the sidebar on the right side of the "edit document" and "create issue", so that the entire blog and activity list occupy the entire width of the page.

### Team, download page

Optimization: typography problems, CSS changes to be made

! [image-20201030203457045](https://tva1.sinaimg.cn/large/0081Kckwly1gk7n0z9jr4j319i0gmmzx.jpg)

The text is above the header.

**Comment by wu-sheng** [comment]
@Jtrust Please help @rootsongjc when you have time. I hope the update could be done before DevCon, 14th Nov.

**Comment by Jtrust** [comment]
> @Jtrust Please help @rootsongjc when you have time. I hope the update could be done before DevCon, 14th Nov.

With pleasure

**Comment by rootsongjc** [comment]
![image](https://user-images.githubusercontent.com/3328185/98064049-61ccd280-1e8c-11eb-943c-5d3cc7118d02.png)

All of the layout issues have been fixed, there's one problem left is that the logo of SkyWaling with SVG is missing. See the above image.

**Comment by rootsongjc** [comment]
The logo problem has been fixed, I used a PNG image to replace the SVG one.

**Comment by rootsongjc** [comment]
The homepage scroll error fixed. We'd fix the language switch button now.

**Comment by rootsongjc** [comment]
After confirming with @wu-sheng  that SkyWalking's website does not need to support multiple languages, I removed the language switch button. Just leave the English pages. There will be a tab on the header named `中文博客`, all of the Chinese blogs will be archived there which will reuse the blog layout. You can see the preview at <https://skywalking.netlify.com>, I will move the legacy Chinese blogs to the new site steps by steps. I can finish it tomorrow.

**Comment by wu-sheng** [comment]
Thanks, @rootsongjc. It is great to see things are getting ready.

**Comment by rootsongjc** [comment]
The first version is basically finished, but there are still some problems left, which we can fix slowly. I will submit a PR.
The next issues to be fixed include:
- [ ] P2:  update the layout of the download page, to allow the download addresses of different projects to be flattened on the page using modules.
- [ ] P2:  Events & News section  of the homepage, we should make it auto-generated, display the latest 4 events from the event lists
- [ ] P1: Migrate the documentation

**Comment by wu-sheng** [comment]
In the next iteration, I prefer to add screenshots review on the homepage.

**Comment by wu-sheng** [comment]
Here, I want to update the progress. @Jtrust did a lot of works to help to make the website better and fancy.

- [x] P2:  update the layout of the download page, to allow the download addresses of different projects to be flattened on the page using modules.
- [x] P2:  Events & News section  of the homepage, we should make it auto-generated, display the latest 4 events from the event lists
- [ ] P1: Migrate the documentation, version support needed
- [x] P2: Make the projects and documentation page configurable, use the YAML or markdown instead of the raw HTML
- [x] P1: fix the footer display problem
- [x] P2: add an arrow on the homepage, jump to the below sections
- [x] P2: add screenshots on the homepage
- [x] P1: add table of content on the blog page

The only one thing left is the doc page generation.

**Comment by Fine0830** [comment]
Wow! That's totally awesome!

**Comment by wu-sheng** [comment]
The last piece is going to be added through https://github.com/apache/skywalking-website/pull/215.
@Jtrust are doing great with this long and complex task. We are going to have the main doc hosted on the website soon, maybe today or tomorrow.
