### ISSUE TITLE
[BanyanDB] Tracking the project bootstrap

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#6697]
I need to figure out below items to set up the project:

 - [x] The bus system for the data ingesting
 - [x] Configuraiton system
 - [x]  Running/Lifecycle framework
 - [x] Async query framework
 - [x]  Logging system
 - [x]  Building tool-chain(linter, Makefile, license checking, etc)
 - [x] CI

Once finishing the above, we could create fined tasks, then assign them to anyone who wants to contribute.

**Comment by hanahmily** [comment]
All sub-tasks are done.
