### ISSUE TITLE
[Core]Trace data processing

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#6922]
This intends to track the progression of the trace data processing. This is the first core feat of banyandb, so several models would be built not only for trace data but also for metric and log data—for example, index, discovery, etc. 

Here's a [diagram](https://github.com/apache/skywalking-banyandb/blob/main/banyand/doc.go) to indicate the interaction between those modules. Although this rough arch intends to compose a distributed database, the first interaction intends to accomplish a sub-set -- a standalone single-node database. There's only a single database instance to accept incoming requests.

Based on that, the standalone banyandb could be separated following modules:

 - [x] Liaison: interaction protocol and  API. communication manager who handles external and internal requests. (assigned to @Fine0830 )
 - [x] Discovery: a broker helps liaison to find desired storage node. We could leverage [embeded etcd](https://github.com/etcd-io/etcd/blob/master/server/embed/doc.go) to implement it.
 - [x] Storage-Series: the storage controller to map logical model to physical model.(#6925 )
 - [x] Storage-Query: the builder to generate the execution plan based on the data from index and series.(#6924)
 - [ ] Storage-Index: reverse indexing library for the query. (assigned to @hanahmily )
 - [x] KV: the underlying  KV storage engine wrapper. (assigned to @hanahmily )
 - [x] OAP integration: link OAP to banyandb. (#7412 )

Anyone who wants to take part in the above modules, pls comment on this issue. I will create a relevant sub-issue for you.

**Comment by wu-sheng** [comment]
> I am interested in the `Storage-Query` part.
> 
> But I may only have some text-book level knowledge for the query engine. Any requirement for the time schedule or experience?

You could read the source codes first. It is always better for understanding codes first. The project is at a very early stage, @hanahmily  will open more tasks, you could keep watch on database tagged issue, https://github.com/apache/skywalking/labels/database

**Comment by hanahmily** [comment]
@lujiajing1126 Nice to see you interested in it.

I created #6924 to show more details about this module. If you would like to take it, I will assign it to you.

Before writing some codes, you should write a design to show details about this module. If you need more discussion, I'm glad to schedule a meeting to help.

**Comment by ascrutae** [comment]
I want to take part in the `Storage-Series` part  development. and I am particularly interested in the mapping of logical models and physical models

**Comment by lujiajing1126** [comment]
> @lujiajing1126 Nice to see you interested in it.
> 
> I created #6924 to show more details about this module. If you would like to take it, I will assign it to you.
> 
> Before writing some codes, you should write a design to show details about this module. If you need more discussion, I'm glad to schedule a meeting to help.

Thank you! I will first read the current design and code as suggested by Wu Sheng.

Then I will try to write the design doc. Sure I will contact you if I need help and discussion.

**Comment by hanahmily** [comment]
@lujiajing1126 Pls comment on #6924 so as to assign it to you.

**Comment by hanahmily** [comment]
Since we redesign the index structures which impacts other parts. I  will set up another issue to track this topic
