### ISSUE TITLE
Support both javaAgent and JavaSdk for distributed tracking in the same process and different process

### ISSUE THREAD

**Issue by chenyi19851209** [apache/skywalking#8260]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When we promote tracing in a distributed system, we found that some java system users are willing to accept the javaAgent mode, and some java system users are more willing to accept the javaSDK embedding mode based on risk or security considerations. I know that skywalking provides trace toolkit. This kind of annotation is for the business system to embed, but it also needs to rely on the bytecode enhancement implantation of javaAgent. Does skywalking's javaAgent consider extracting a javaSDK for tracking like opentelemetry-SdK, allowing users to choose between javaAgent or javaSDK tracking in the same process or between different processes?

### Use case

When we promote tracing in a distributed system, we found that some java system users are willing to accept the javaAgent mode, and some java system users are more willing to accept the javaSDK embedding mode based on risk or security considerations.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
