### ISSUE TITLE
[Bug] Incompatible with versions after dubbo-2.7.14, resulting in broken tracking

### ISSUE THREAD

**Issue by wuwen5** [apache/skywalking#8415]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

After upgrading Dubbo 2.7.15, the trace log was broken.

### What you expected to happen

The ```rpcContext.getAttachments()``` method returns is  copy Map.

https://github.com/apache/dubbo/pull/8772/files

### How to reproduce

upgrade dubbo version >= 2.7.14

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I think you have to ask for Dubbo community to explain this kind of important kernel-level behavior change, and why.
