### ISSUE TITLE
[Feature] OAP BanyanDB Storage module

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#8968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This tracks the progression of BanyanDB storage module:

  * [x] TableInstaller, schema registration (@lujiajing1126)
  * [x] Management, UI Template (@lujiajing1126)
  * [x] Metadata (@lujiajing1126)
    * [x] Service (~~currently issue with `layer` filter~~ https://github.com/apache/skywalking/issues/8979)
    * [x] Instance
    * [x] Endpoint
    * [x] Process (~~depend on `Metrics.multiGet/insert/update` confirmed with @mrproliu~~ Done)
  * [x] Stream/Record (@lujiajing1126)
    * [x] Segment and Trace Query
    * [x] EBPF Profiling (still an issue with `BanyanDBEBPFProfilingDataDAO`, wait for confirmation from @mrproliu )
    * [x] Alarm Record (Should be tested after metrics implementations are ready)
    * [x] Profiling
      * [x] `ProfileTask` (`ProfileTask.getById` needs native support ID query in BanyanDB for stream)
      * [x] `ProfileTaskLog`
      * [x] `ProfileThreadSnapshot` (~~an issue with `byte[]` conversion~~ https://github.com/apache/skywalking/pull/8986)
    * [x] Log
      * [x] Log
      * [x] BrowserLog (~~issue resolved by https://github.com/SkyAPMTest/skywalking-client-test/pull/17~~ verified)
  * [x] NoStreamDAO.insert (@lujiajing1126)
  * [x] Batch (@lujiajing1126)
  * [x] Metrics (@lujiajing1126)
    * [x] prepareBatchUpdate
    * [x] prepareBatchInsert
    * [x] multiGet
  * [x] MetricsQuery (@lujiajing1126)
  * [x] TagAutoCompleteQuery (@lujiajing1126, need support from #9066 )
  * [x] Event (Need support from #9065)
  * [x] AggregationQuery
  * [x] ~~History deletion~~ （Rely on TTL of BanyanDB)
  * [x] NetworkAddressAlias (@dmsolr)
  * [x] ServiceLabels (@dmsolr)
  * [x] TopN
  * [x] Topology (@lujiajing1126)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
@dmsolr @lujiajing1126 Would you please fill the above checklist?

**Comment by lujiajing1126** [comment]
> @dmsolr @lujiajing1126 Would you please fill the above checklist?

Sure
