### ISSUE TITLE
[TODO] Remove `hacktoberfest` label when the event is over.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9693]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

`hacktoberfest` label was added due to SkyWalking being involved in [hacktoberfest 2022](https://hacktoberfest.com/)

### What you expected to happen

Keep this open to track this label should be removed after the event finished.

### How to reproduce

Nothing special

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
Oops my bad, I forgot to open this issue. Thanks.
