### ISSUE TITLE
[Bug] in the  trace profiling task list do not have a remove button  

### ISSUE THREAD

**Issue by zhupingcmm** [apache/skywalking#9951]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

![image](https://user-images.githubusercontent.com/30522912/201452803-e93029ba-1638-4ad4-b438-89795c129e2f.png)
In the trace profiling task list, do not have a button to remove the task item. Currently  only can add task and can not remove task

### What you expected to happen

want a delete button for task list

### How to reproduce

entry into  trace profiling

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
There is no point to remove manually. It would be removed automatically by TTL.

**Comment by wu-sheng** [comment]
Use discussion panel to ask questions. This is not a bug.

**Comment by zhupingcmm** [comment]
> There is no point to remove manually. It would be removed automatically by TTL.

ok. thx
